version: 2.1
jobs:
  compile:
   docker:
      - image: azrim89/kernel:latest
   steps:
      - run:
          no_output_timeout: 50m 
          environment: 
            TG_TOKEN: 1120857851:AAFr99rMHnOLiUQJx_WzRKLsZf83toWwY_s
            CHANNEL_ID: -1001698415738
          command: bash build_script.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
